import type { NextPage } from 'next';
import Head from 'next/head';

import MultiplicationTable from '../components/MultiplicationTable';
import ProblemGenerator from '../components/ProblemGenerator';

const Home: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>Can you do the maths?</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <main className="">
        <h1 className="">Do you even math? 🤷‍♂️</h1>
        <div className="print-page-break section-multiplication-table"></div>
      </main> */}

      <ProblemGenerator />
      <MultiplicationTable />
    </div>
  );
};

export default Home;
